### ISSUE TITLE
moveit-kinetic-source fails to build

### ISSUE THREAD

**Issue by dbolkensteyn** [davetcoleman/moveit_docker#4]
See https://hub.docker.com/r/moveit/moveit_docker/builds/bbhmsbjwyarlbzorehqdus9/

```
Setting up python-osrf-pycommon (0.1.2-1) ...
Setting up python-catkin-tools (0.4.2-1) ...
ERROR: default sources list file already exists:
    /etc/ros/rosdep/sources.list.d/20-default.list
Please delete if you wish to re-initialize
Removing intermediate container 081bf18671cb
The command '/bin/sh -c apt-get update &&     apt-get install -y python-catkin-tools less wget &&     rosdep init &&     rosdep update &&     rosdep install -y --from-paths . --ignore-src --rosdistro ${ROS_DISTRO} &&     rm -rf /var/lib/apt/lists/*' returned a non-zero code: 1
```

On my machine, running

```
docker build -t moveit/moveit_docker:moveit-kinetic-source .
```

leads to a similar error, although I'm not 100% sure it's the same as on the Docker Hub's build env:

```
Setting up python-osrf-pycommon (0.1.2-1) ...
Setting up python-catkin-tools (0.4.2-1) ...

ERROR: Rosdep experienced an error: [Errno 2] No such file or directory
Please go to the rosdep page [1] and file a bug report with the stack trace below.
[1] : http://www.ros.org/wiki/rosdep

rosdep version: 0.11.5

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/rosdep2/main.py", line 136, in rosdep_main
    exit_code = _rosdep_main(args)
  File "/usr/lib/python2.7/dist-packages/rosdep2/main.py", line 353, in _rosdep_main
    return _package_args_handler(command, parser, options, args)
  File "/usr/lib/python2.7/dist-packages/rosdep2/main.py", line 447, in _package_args_handler
    return command_handlers[command](lookup, packages, options)
  File "/usr/lib/python2.7/dist-packages/rosdep2/main.py", line 654, in command_install
    installer.install(uninstalled, **install_options)
  File "/usr/lib/python2.7/dist-packages/rosdep2/installers.py", line 485, in install
    verbose=verbose, quiet=quiet)
  File "/usr/lib/python2.7/dist-packages/rosdep2/installers.py", line 535, in install_resolved
    result = subprocess.call(sub_command)
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1340, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory


executing command [sudo -H apt-get install -y freeglut3-dev]
The command '/bin/sh -c apt-get update &&     apt-get install -y         python-catkin-tools         less &&     rosdep install -y --from-paths . --ignore-src --rosdistro ${ROS_DISTRO} &&     rm -rf /var/lib/apt/lists/*' returned a non-zero code: 1
```

**Comment by davetcoleman** [comment]
Yea I still haven't figured out what is causing that error - it seems very intermittent. I just retried and have re-triggered Docker to build. Any help is appreciated

**Comment by dbolkensteyn** [comment]
On my machine, it seems that `rosdep` is trying to invoke `apt-get` by using `sudo -H` as a prefix, whereas `sudo` isn't installed.

So I've just tried to install it before (`apt-get install python-catkin-tools less sudo`) and the build passes.

However installing sudo seems to be a bad practice according to this page:
  https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/

I'll look into rosdep: perhaps there's a parameter to avoid prefixing every `apt-get` command by `sudo -H`

**Comment by davetcoleman** [comment]
Thanks for looking into that. I added sudo as a temporary workaround: https://github.com/ros-planning/moveit_docker/commit/f0991b7936606f983e93b4d8b949c7df2c621da2

btw I just noticed this issue is in the wrong repo... should be https://github.com/ros-planning/moveit_docker

**Comment by dbolkensteyn** [comment]
Thanks @davetcoleman - done
